### ISSUE TITLE
sugestia unsplash-search

### ISSUE THREAD

**Issue by MaciejFigat** [konradlu/unsplash-search#1]
Hej tu Maciek z kursu CL,
przeglądałem twoje repo bo mi mój własny kod nie działa i pomyślałem sobie, 
że podzielę się sugestią odnośnie accessKey które masz w kodzie w App.jsx.
Ukryłbym go w pliku .env a na netlify możesz zmienne zadeklarować w 
** Site settings > Build & deploy > Environment > Environment variables. **
Ostatnio myślałem o podobnej rzeczy, o zmiennych środowiskowych w samym react app. 
Nie wiem czy wiesz ale React używa .env więc możesz spokojnie sobie zadeklarować zmienne w pliku .env. 
Dostęp do nich masz za pomocą process.env.
[Doc o env w React](https://create-react-app.dev/docs/adding-custom-environment-variables/)

### Zrobiłbym tak: 
1. plik .env - stworzyłbym w roocie projektu
2. tam bym dał
`REACT_APP_MY_SECRET_KEY = 12345`
3. w pliku App.jsx 
`const accessKey = process.env.REACT_APP_SECRET_KEY`
4. dodaj .env do .gitignore

Myślę, że powinno zadziałać, niewiele o tym wiem ale ostatnio wróciłem do projektu i chciałem coś ukryć, a nie wiedziałem czy mogę.

Piszę i pozdrawiam.

**Comment by konradlb** [comment]
Miałem to zrobione, ale nie wypushowane :)
Dodałem jest plik template.env aby kopiując repo dodać tylko swoje klucze i
zmienić nazwę.

**Comment by MaciejFigat** [comment]
Great minds think alike!
